./AccelerometerPlay/AndroidManifest.xml
./Alarm/AndroidManifest.xml
./AndroidBeamDemo/AndroidManifest.xml
./AppNavigation/AndroidManifest.xml
./BackupRestore/AndroidManifest.xml
./BasicGLSurfaceView/AndroidManifest.xml
./BluetoothChat/AndroidManifest.xml
./BluetoothHDP/AndroidManifest.xml
./BrokenKeyDerivation/AndroidManifest.xml
./BusinessCard/AndroidManifest.xml
./Compass/AndroidManifest.xml
./ContactManager/AndroidManifest.xml
./ControllerSample/AndroidManifest.xml
./CrossCompatibility/AndroidManifest.xml
./CubeLiveWallpaper/AndroidManifest.xml
./DimensionsDifferences/AndroidManifest.xml
./FixedGridLayout/AndroidManifest.xml
./GestureBuilder/AndroidManifest.xml
./HelloActivity/AndroidManifest.xml
./HelloEffects/AndroidManifest.xml
./Home/AndroidManifest.xml
./HoneycombGallery/AndroidManifest.xml
./KeyChainDemo/AndroidManifest.xml
./LceDemo/AndroidManifest.xml
./ListGrid/AndroidManifest.xml
./MultiResolution/AndroidManifest.xml
./MultiWindow/AndroidManifest.xml
./NinePatchLab/AndroidManifest.xml
./NotePad/AndroidManifest.xml
./NotepadCodeLab/Notepadv1/AndroidManifest.xml
./NotepadCodeLab/Notepadv1Solution/AndroidManifest.xml
./NotepadCodeLab/Notepadv2/AndroidManifest.xml
./NotepadCodeLab/Notepadv2Solution/AndroidManifest.xml
./NotepadCodeLab/Notepadv3/AndroidManifest.xml
./NotepadCodeLab/Notepadv3Solution/AndroidManifest.xml
./Obb/AndroidManifest.xml
./OpenGL/HelloOpenGLES10/AndroidManifest.xml
./OpenGL/HelloOpenGLES20/AndroidManifest.xml
./RSSReader/AndroidManifest.xml
./ReceiveShareDemo/AndroidManifest.xml
./SearchableDictionary/AndroidManifest.xml
./SecureMessages/AndroidManifest.xml
./SipDemo/AndroidManifest.xml
./SkeletonApp/AndroidManifest.xml
./Snake/AndroidManifest.xml
./SpellChecker/HelloSpellChecker/AndroidManifest.xml
./Spinner/AndroidManifest.xml
./StackWidget/AndroidManifest.xml
./TicTacToeLib/AndroidManifest.xml
./USB/AdbTest/AndroidManifest.xml
./VoiceRecognitionService/AndroidManifest.xml
./VoicemailProviderDemo/AndroidManifest.xml
./WeatherListWidget/AndroidManifest.xml
./WiFiDirectDemo/AndroidManifest.xml
./WiFiDirectServiceDiscovery/AndroidManifest.xml
./WritingAgileAPKs/code/ActionBar/AndroidManifest.xml
./WritingAgileAPKs/code/Animation/AndroidManifest.xml
./android-code/AudioDemo/AndroidManifest.xml
./android-code/Bubble/AndroidManifest.xml
./android-code/Camera/AndroidManifest.xml
./android-code/Clock/AndroidManifest.xml
./android-code/Compass/AndroidManifest.xml
./android-code/DeviceAdministeredSecureNote/AndroidManifest.xml
./android-code/DrawDemo/AndroidManifest.xml
./android-code/HelloWorld/AndroidManifest.xml
./android-code/Template/AndroidManifest.xml
./android-code/ToddlerLockDemo/AndroidManifest.xml
./android-code/TrafficDemo/AndroidManifest.xml
./android-code/UIApp/AndroidManifest.xml
./android-code/UIComponents/AndroidManifest.xml
./android-code/UnitConverter/AndroidManifest.xml
./android-code/WhereAmI/AndroidManifest.xml
./android-code/WidgetDemo/AndroidManifest.xml
./android-code/WifiInfo/AndroidManifest.xml
./browseable/AppRestrictions/AndroidManifest.xml
./browseable/AutoBackupForApps/AndroidManifest.xml
./browseable/BasicManagedProfile/AndroidManifest.xml
./browseable/ConfirmCredential/AndroidManifest.xml
./browseable/DirectShare/AndroidManifest.xml
./browseable/DocumentCentricApps/AndroidManifest.xml
./browseable/DocumentCentricRelinquishIdentity/AndroidManifest.xml
./browseable/MidiScope/AndroidManifest.xml
./browseable/MidiSynth/AndroidManifest.xml
./devbytes/animation/ActivityAnimations/AndroidManifest.xml
./devbytes/animation/Anticipation/AndroidManifest.xml
./devbytes/animation/Bouncer/AndroidManifest.xml
./devbytes/animation/CardFlip/AndroidManifest.xml
./devbytes/animation/CrossFading/AndroidManifest.xml
./devbytes/animation/CurvedMotion/AndroidManifest.xml
./devbytes/animation/KeyframeAnimation/AndroidManifest.xml
./devbytes/animation/LayoutTransChanging/AndroidManifest.xml
./devbytes/animation/ListViewAnimations/AndroidManifest.xml
./devbytes/animation/ListViewCellInsertion/AndroidManifest.xml
./devbytes/animation/ListViewDraggingAnimation/AndroidManifest.xml
./devbytes/animation/ListViewExpandingCells/AndroidManifest.xml
./devbytes/animation/ListViewItemAnimations/AndroidManifest.xml
./devbytes/animation/ListViewRemovalAnimation/AndroidManifest.xml
./devbytes/animation/LiveButton/AndroidManifest.xml
./devbytes/animation/MultiPropertyAnimations/AndroidManifest.xml
./devbytes/animation/PictureViewer/AndroidManifest.xml
./devbytes/animation/PropertyAnimations/AndroidManifest.xml
./devbytes/animation/SlidingFragments/AndroidManifest.xml
./devbytes/animation/SquashAndStretch/AndroidManifest.xml
./devbytes/animation/ViewAnimations/AndroidManifest.xml
./devbytes/animation/WindowAnimations/AndroidManifest.xml
./devbytes/graphics/BitmapAllocation/AndroidManifest.xml
./devbytes/graphics/BitmapScaling/AndroidManifest.xml
./devbytes/graphics/FoldingLayout/AndroidManifest.xml
./devbytes/graphics/ImagePixelization/AndroidManifest.xml
./devbytes/ui/ListViewDeletion/AndroidManifest.xml
./helloWorlds/AndroTermux/AndroidManifest.xml
./helloWorlds/SettingInjectorSample/AndroidManifest.xml
./helloWorlds/testproject/AndroidManifest.xml
./picview-for-android/picview/AndroidManifest.xml
./sendreduced/AndroidManifest.xml
./training/NsdChat/AndroidManifest.xml
./training/device-management-policy/AndroidManifest.xml
./training/network-usage/AndroidManifest.xml
./training/testingfun/app/AndroidManifest.xml
